### ISSUE TITLE
Структура репозитория

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/Gaz#1]
(Тикет-напоминалка. Подробностей здесь нет. Сделать проще вживую.)

**Comment by GerasimovIV** [comment]
привел в нормальный вид

**Comment by avasyukov** [comment]
Почти. Осталось:
- Снести бинарник.
- В папке headers/ сейчас не только хэдеры! Складывать заголовки и реализацию *внутрь* друг друга (сейчас sources внутри headers) - не очень хорошая идея. Файлы .{h,hpp} и .cpp могут лежать в одной папке - это норм. Если ну очень хочется их разделить - ну ок, можно вернуться к сценарию ".{h,hpp} в папке include/ или headers/, а .cpp в src/ или sources/ *рядом* с ней". Но точно не одно внутри другого.

Да, я придираюсь. Но всё же добиваем до вида, когда это выглядит правда круто (в смысле общепринятой организации кода в средне-крупном проекте).

**Comment by GerasimovIV** [comment]
объединил исходники с хэдэрами, убрал бинарник

**Comment by avasyukov** [comment]
Я знаю, что заколебал. А по коммитам похоже, что сил просто нет. Тем не менее:
- переименуйте чёртову папочку headers в sources, src или аналог - ну не хорошо, когда на клетке со львом написано "тигр"
- верните CMakeLists.txt, репозиторий должен быть собираем (если он был протерян, можно найти в истории коммитов - https://github.com/IvanOfficial/Gaz/blob/a741a7ff2b17589c5432ec210638d1b08f8eb40d/CMakeLists.txt - только пути поправить)

**Comment by GerasimovIV** [comment]
сделал

**Comment by avasyukov** [comment]
Ура. Проверил - всё, официально добито до победного конца.
